// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings is the whole preference set. It is small on purpose: every option
 * here is one the user asked for, not one we guessed at.
 */
export interface Settings {
    /**
     * LaunchOnLogin starts the app minimised when the user signs in.
     */
    "launchOnLogin": boolean;

    /**
     * CloseToTray keeps the app running when the window is closed, which is
     * what a tray-resident VPN client is expected to do.
     */
    "closeToTray": boolean;

    /**
     * AutoConnectProfileID is connected on startup, empty for none.
     */
    "autoConnectProfileId": string;

    /**
     * Theme is the appearance preference.
     */
    "theme": Theme;

    /**
     * LastProfileID is remembered so the UI can preselect it.
     */
    "lastProfileId": string;
}

/**
 * Theme is the appearance preference. "system" follows the OS.
 */
export enum Theme {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeSystem = "system",
    ThemeLight = "light",
    ThemeDark = "dark",
};
