// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Answer is a reply to a Prompt.
 */
export interface Answer {
    "promptId": string;
    "username": string;
    "password": string;

    /**
     * Response is the second factor, for challenge prompts.
     */
    "response": string;

    /**
     * Remember asks us to store the credentials for next time.
     */
    "remember": boolean;
}

/**
 * LogLine is one line from openvpn, tagged for display.
 */
export interface LogLine {
    "at": string;
    "level": string;
    "text": string;
}

/**
 * Phase is the connection state as the UI thinks about it. openvpn reports a
 * dozen states; a person only cares about a handful.
 */
export enum Phase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PhaseIdle = "idle",
    PhaseStarting = "starting",
    PhaseConnecting = "connecting",
    PhaseAuthenticating = "authenticating",
    PhaseConfiguring = "configuring",
    PhaseConnected = "connected",
    PhaseReconnecting = "reconnecting",
    PhaseDisconnecting = "disconnecting",
    PhaseFailed = "failed",
};

/**
 * Prompt is a request for credentials, shaped for a dialog.
 */
export interface Prompt {
    /**
     * ID must be echoed back with the answer, so a stale dialog cannot answer a
     * newer prompt.
     */
    "id": string;
    "kind": PromptKind;

    /**
     * Realm is openvpn's scope for the credential, e.g. "Auth".
     */
    "realm": string;

    /**
     * Title and Message are for the dialog.
     */
    "title": string;
    "message": string;

    /**
     * Username is prefilled when the server told us who it thinks we are.
     */
    "username": string;

    /**
     * ChallengeText is the question to put next to the second-factor field.
     */
    "challengeText"?: string;

    /**
     * EchoResponse reports whether the second factor may be shown as typed.
     */
    "echoResponse": boolean;

    /**
     * Retry marks a prompt that follows a rejected attempt.
     */
    "retry": boolean;
}

/**
 * PromptKind distinguishes the credential shapes openvpn can ask for.
 */
export enum PromptKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * PromptCredentials is a username and password.
     */
    PromptCredentials = "credentials",

    /**
     * PromptPassphrase is a private key passphrase; no username.
     */
    PromptPassphrase = "passphrase",

    /**
     * PromptStaticChallenge wants username, password and a second factor at once.
     */
    PromptStaticChallenge = "static-challenge",

    /**
     * PromptDynamicChallenge wants only a second factor, after the password was
     * accepted but judged insufficient.
     */
    PromptDynamicChallenge = "dynamic-challenge",
};

/**
 * Status is the whole connection state, as one value the UI can render.
 */
export interface Status {
    "phase": Phase;

    /**
     * ProfileID and ProfileName identify what we are connected to.
     */
    "profileId": string;
    "profileName": string;

    /**
     * Detail is a sentence for a person, not an openvpn state name.
     */
    "detail": string;

    /**
     * Since is when this phase began.
     */
    "since": string;

    /**
     * ConnectedAt is when the tunnel came up, zero if it has not.
     */
    "connectedAt": string;
    "localIp": string;
    "remoteIp": string;
    "remotePort": string;
    "bytesIn": number;
    "bytesOut": number;

    /**
     * Prompt is set when openvpn is waiting on the user for credentials.
     */
    "prompt"?: Prompt | null;

    /**
     * Error explains a failure, in the words we would show a user.
     */
    "error"?: string;

    /**
     * Stalled marks a connection that has stopped making progress without
     * failing. openvpn can end up waiting for an answer to a question that was
     * never delivered, which otherwise looks like an indefinite spinner.
     */
    "stalled": boolean;
}
