// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService covers everything that is about the app rather than a specific
 * connection: readiness, preferences, and where things live on disk.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../internal/settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Health reports whether the app can do its job, and if not, why.
 */
export function Health(): $CancellablePromise<$models.Health> {
    return $Call.ByID(746998627);
}

/**
 * OpenLogFolder reveals the log directory in the file manager, for when a user
 * needs to send a log to someone.
 */
export function OpenLogFolder(): $CancellablePromise<void> {
    return $Call.ByID(2267655993);
}

/**
 * OpenProfileFolder reveals where profiles are stored.
 */
export function OpenProfileFolder(): $CancellablePromise<void> {
    return $Call.ByID(1801616982);
}

/**
 * SaveSettings replaces the preferences and applies the ones that have an
 * effect outside our own files.
 */
export function SaveSettings(next: settings$0.Settings): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1100866057, next);
}

/**
 * Settings returns the current preferences.
 */
export function Settings(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(3215841820);
}
