// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService drives the tunnel.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vpn$0 from "../internal/vpn/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect brings up a profile, replacing any current connection.
 */
export function Connect(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(3343380486, profileID);
}

/**
 * Disconnect brings down the current connection.
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(368604074);
}

/**
 * Logs returns the current session's log lines.
 */
export function Logs(): $CancellablePromise<vpn$0.LogLine[] | null> {
    return $Call.ByID(3347489747);
}

/**
 * SavedCredentialsForCurrent returns whatever is stored for the secret the
 * current prompt is asking about.
 */
export function SavedCredentialsForCurrent(): $CancellablePromise<$models.AutoFill> {
    return $Call.ByID(118538831);
}

/**
 * Status returns the current connection state. The UI also receives this as an
 * event on every change; this method is for the initial render and for
 * recovering after a reload.
 */
export function Status(): $CancellablePromise<vpn$0.Status> {
    return $Call.ByID(1070053106);
}

/**
 * SubmitCredentials answers an outstanding sign-in prompt.
 * 
 * Saving is done here rather than in the UI so the secret crosses the boundary
 * once and is never handed back.
 */
export function SubmitCredentials(answer: vpn$0.Answer): $CancellablePromise<void> {
    return $Call.ByID(3103736494, answer);
}
