// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AutoFill returns saved credentials for the profile currently prompting, so
 * the dialog can offer them. It returns the password because the user has
 * already chosen to save it and the dialog needs to submit it; nothing is
 * persisted to the frontend beyond the life of the dialog.
 */
export interface AutoFill {
    "found": boolean;
    "username": string;
    "password": string;

    /**
     * FromLegacyGUI marks values recovered from the OpenVPN community GUI
     * rather than from our own vault. The dialog says so, because filling in a
     * secret the user did not give this app should never be silent.
     */
    "fromLegacyGui": boolean;
}

/**
 * Health is what the UI needs to decide whether to show the normal interface or
 * an explanation of what is missing.
 */
export interface Health {
    /**
     * Ready reports whether a connection could be started right now.
     */
    "ready": boolean;

    /**
     * Problem explains why not, written for a person.
     */
    "problem": string;

    /**
     * OpenVPNVersion is the detected openvpn version banner, empty if absent.
     */
    "openvpnVersion": string;

    /**
     * OpenVPNPath is where openvpn.exe was found.
     */
    "openvpnPath": string;

    /**
     * ProfileDir is where profiles are stored.
     */
    "profileDir": string;

    /**
     * LogDir is where openvpn's own logs are written.
     */
    "logDir": string;

    /**
     * AppVersion is our version.
     */
    "appVersion": string;

    /**
     * Platform is the OS this is running on.
     */
    "platform": string;
}

/**
 * ImportResult reports what happened to a drop, which may have been partly
 * successful.
 */
export interface ImportResult {
    "imported": ProfileView[] | null;

    /**
     * Errors are one per path we could not import, already written for a person.
     */
    "errors": string[] | null;
}

/**
 * ProfileView is a profile as the UI shows it.
 */
export interface ProfileView {
    "id": string;
    "name": string;

    /**
     * Server is the primary server address, for the subtitle in the list.
     */
    "server": string;

    /**
     * Protocol is "udp" or "tcp", empty when the profile does not say.
     */
    "protocol": string;

    /**
     * ImportedAt is an RFC3339 timestamp.
     */
    "importedAt": string;

    /**
     * NeedsCredentials tells the UI a sign-in will be required.
     */
    "needsCredentials": boolean;

    /**
     * HasSavedCredentials reports whether credentials are in the vault.
     */
    "hasSavedCredentials": boolean;

    /**
     * RoutesAllTraffic reports whether the profile sends everything through
     * the tunnel.
     */
    "routesAllTraffic": boolean;

    /**
     * Warnings are import-time findings worth showing.
     */
    "warnings": string[] | null;
}
