// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProfileService manages the list of VPN profiles.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BrowseAndImport opens a file picker and imports whatever the user chooses.
 * 
 * The dialog lives on the Go side so the frontend never handles filesystem
 * paths, which keeps the drag-and-drop path and the browse path identical.
 * 
 * Directories are deliberately not selectable. On Windows, Wails switches to a
 * folder picker as soon as CanChooseDirectories is set -- whatever
 * CanChooseFiles says -- so allowing both meant the user was asked for the
 * folder containing their profile rather than for the profile itself, and could
 * only pick one at a time. A dropped folder still works; that path goes through
 * ImportPaths, which looks inside it.
 */
export function BrowseAndImport(): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(3474838591);
}

/**
 * Delete removes a profile, its keys, and any saved credentials.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3038240408, id);
}

/**
 * ForgetCredentials removes saved credentials without touching the profile.
 */
export function ForgetCredentials(id: string): $CancellablePromise<void> {
    return $Call.ByID(2800593116, id);
}

/**
 * Import takes the paths from a file drop or a file dialog and stores whatever
 * is importable among them.
 */
export function Import(paths: string[] | null): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(880384338, paths);
}

/**
 * List returns the stored profiles, newest first.
 */
export function List(): $CancellablePromise<$models.ProfileView[] | null> {
    return $Call.ByID(1689737715);
}

/**
 * Rename changes a profile's display name.
 */
export function Rename(id: string, name: string): $CancellablePromise<$models.ProfileView> {
    return $Call.ByID(2624522273, id, name);
}

/**
 * SavedUsername returns the stored username for a profile, so the sign-in
 * dialog can prefill it. The password is never returned to the frontend.
 */
export function SavedUsername(id: string): $CancellablePromise<string> {
    return $Call.ByID(4129893042, id);
}
